# Estilo minimalista com ícones brancos

# Ícones brancos
typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=15
typeset -g POWERLEVEL9K_HOME_ICON_FOREGROUND=15
typeset -g POWERLEVEL9K_FOLDER_ICON_FOREGROUND=15

# Seta ❯ branca
typeset -g POWERLEVEL9K_PROMPT_CHAR_FOREGROUND=15

# Caminho do diretório em branco
typeset -g POWERLEVEL9K_DIR_FOREGROUND=15
typeset -g POWERLEVEL9K_DIR_HOME_FOREGROUND=15
typeset -g POWERLEVEL9K_SHORTENED_DIR_FOREGROUND=15

# Estilo visual clean
typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=' '
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=' '
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=' '
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=' '
