# Minimalista e escuro - por aon

# Desativa tudo o que for visual extra
POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true
typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet

# Tema do prompt
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

# Diretório atual
typeset -g POWERLEVEL9K_DIR_FOREGROUND=7
typeset -g POWERLEVEL9K_DIR_BACKGROUND=0
typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=40
typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false
typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"

# Git
typeset -g POWERLEVEL9K_VCS_FOREGROUND=7
typeset -g POWERLEVEL9K_VCS_BACKGROUND=0
typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=""
typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=7
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=0
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=7
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=0
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=1
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=0

# Estilo do prompt (uma linha, nenhum símbolo à esquerda)
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR=''
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false
typeset -g POWERLEVEL9K_LEFT_SEGMENT_END_SEPARATOR=''
typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR=''
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_END_SEPARATOR=''
typeset -g POWERLEVEL9K_PROMPT_CHAR='❯'

# Sem prompt final (deixa limpo)
typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=0
typeset -g POWERLEVEL9K_PROMPT_CHAR_FOREGROUND=7
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_FOREGROUND=7
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIVIS_FOREGROUND=1
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIVIS_CONTENT_EXPANSION='❯'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIVIS_CONTENT_EXPANSION='❯'

# Nada à direita
typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_FIRST_SEGMENT_END_SYMBOL=''

# Modo silencioso de inicialização
typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true
